name: CI
on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HTML/CSS sanity
        run: echo "Glint CI ok"
